// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewBuilder.Models;

namespace ReviewBuilder.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("ReviewBuilder.Models.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ReviewFieldsId");

                    b.HasKey("Id");

                    b.HasIndex("ReviewFieldsId");

                    b.ToTable("Evaluation");
                });

            modelBuilder.Entity("ReviewBuilder.Models.FileData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<string>("Path");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FileData");

                    b.HasDiscriminator<string>("Discriminator").HasValue("FileData");
                });

            modelBuilder.Entity("ReviewBuilder.Models.ReviewFields", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChiefName");

                    b.Property<string>("Discipline");

                    b.Property<int?>("FieldFileDataId");

                    b.Property<string>("StudentGroup");

                    b.Property<string>("StudentName");

                    b.Property<string>("Theme");

                    b.HasKey("Id");

                    b.HasIndex("FieldFileDataId");

                    b.ToTable("ReviewFields");
                });

            modelBuilder.Entity("ReviewBuilder.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("builded");

                    b.Property<DateTime>("dt");

                    b.HasKey("Id");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("ReviewBuilder.Models.FieldFileData", b =>
                {
                    b.HasBaseType("ReviewBuilder.Models.FileData");

                    b.Property<string>("UserId1");

                    b.HasIndex("UserId1");

                    b.ToTable("FieldFileData");

                    b.HasDiscriminator().HasValue("FieldFileData");
                });

            modelBuilder.Entity("ReviewBuilder.Models.Evaluation", b =>
                {
                    b.HasOne("ReviewBuilder.Models.ReviewFields")
                        .WithMany("EvaluatonsSet")
                        .HasForeignKey("ReviewFieldsId");
                });

            modelBuilder.Entity("ReviewBuilder.Models.FileData", b =>
                {
                    b.HasOne("ReviewBuilder.Models.User")
                        .WithMany("buildFiles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ReviewBuilder.Models.ReviewFields", b =>
                {
                    b.HasOne("ReviewBuilder.Models.FieldFileData")
                        .WithMany("reviewFields")
                        .HasForeignKey("FieldFileDataId");
                });

            modelBuilder.Entity("ReviewBuilder.Models.FieldFileData", b =>
                {
                    b.HasOne("ReviewBuilder.Models.User")
                        .WithMany("fieldFiles")
                        .HasForeignKey("UserId1");
                });
#pragma warning restore 612, 618
        }
    }
}
